INSERT INTO role (name) VALUES ('ROLE_MEMBER') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_LIBRARIAN') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
